[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
